services:
  postgres:
    container_name: vacancy_management_postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: vacancy_management
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: